global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'apache'
    static_configs:
      - targets: ['apache-exporter:9117']

  - job_name: "tomcat"
    static_configs:
      - targets: ["tomcat:9010"]

